Portfolio Mobile Website
evansnyamekye/Portfolio-MobileFirst pull request #1
Opened 2023-03-23 10:30 UTC by evansnyamekye

2023-03-24 15:00 UTC, divinecharlotte requested changes
Hi @evansnyamekye   ,
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## To Highlight :100:
- No linters errors :heavy_check_mark:
- Descriptive commit messages :heavy_check_mark:
- clean code :heavy_check_mark:
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes :recycle:


_Check the comments under the review._
## Optional suggestions




**Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!:clap::clap::clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 15:00 UTC, divinecharlotte commented on index.html
> +    </div>
- [ ] kindly consider changing this container of this into a header tag to full-fill the below requirement
- > The container of the section is a `header` tag

2023-03-24 15:00 UTC, divinecharlotte commented on index.html
> +      <a href="#"><img src="images/logo/Union.png" /></a>
- [ ] kindly consider adding this hamburger menu in a nav as it will contains links to navigate to different parts of your portfolio  remember the main reason for this is that The `nav` tag is for semantics reason

2023-03-24 15:00 UTC, divinecharlotte commented on index.html
> +        </div>
- [ ] kindly consider adding the list of icons in a `ul` tag to group them, and `li` per icon; and make sure each icon has a link (`a` tag) and this will help them to be semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2023-03-24 15:00 UTC, divinecharlotte commented on style.css
> +    background-image: url(images/bg/header-shapes\ mobile.png);
- [ ] kindly consider making the background image not repeating it self to make a good duplicate of the provided design 
check the images below for more clarification 
- your design 👇
<img width="388" alt="Screen Shot 2023-03-24 at 16 53 56" src="https://user-images.githubusercontent.com/60146030/227561124-ef510e08-c335-40fb-a6e0-cf46a320c709.png">
- provided design 👇 
<img width="423" alt="Screen Shot 2023-03-24 at 16 57 59" src="https://user-images.githubusercontent.com/60146030/227561393-b8b2c916-95b0-4f7f-b87c-062c461c972f.png">

2023-03-25 05:28 UTC, shella12 approved these changes
Hi @evansnyamekye, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/dm5BwJbS0VjRZYqle7/giphy.gif"/>

## Highlights

- Linters are passing ✔️ 
- README is professional 👍 
- Great design implementation 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 06:55 UTC, merged