Porfolio Website: Pop-up-menu
evansnyamekye/Portfolio-MobileFirst pull request #15
Opened 2023-05-18 04:35 UTC by evansnyamekye

###Add pop-up-menu to website.

2023-05-18 16:44 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 16:44 UTC, Qoosim commented on index.html
>          <div class="card-right">
- [ ] It is required that already created HTML code for the projects list should be removed, and instead it should be added via JavaScript. kIndly remove all the code for projects list here and create them dynamically on page load from your javascript file.
- [ ] Both the projects list on the page and the popup window must be created dynamically via javascript.


### Project Requirement
![project-rqt](https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/26597432/7c674db7-008c-4ad9-a67c-432a9dc280d0)

2023-05-18 16:44 UTC, Qoosim commented on main.js
> +}
- [ ] It is required to stick to the Figma design as close as possible. Your design for the popup window on both screen sizes are different from how they appear on the figma file. Kindly give a closer look into the figma designs and walk your designs alongside the figma design.

### Your Design Desktop

![your-popup-desktop](https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/26597432/d9effab3-5cbe-4fb7-be18-f0582e245f24)


### Figma Design Desktop

![temp-popup-desktop](https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/26597432/511184e1-2b59-4eb1-81c0-f8063ffc9475)


### Your Design Mobile

![your-popuu-mobile](https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/26597432/fa9343fa-d298-4fe6-9063-31979c18ddd5)


### Figma Design Mobile

![temp-popup-mobile](https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/26597432/e878d636-b5b8-4bb7-8fa4-6cc64d7f3eaa)

2023-05-19 21:01 UTC, aamirkhan2478 requested changes
Hi @evansnyamekye & @aamir-asaram , 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linter passed

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 21:01 UTC, aamirkhan2478 commented on index.html
https://github.com/evansnyamekye/Portfolio-CompleteWebsite/blob/df73ca0a5ba30c23a7512593153a200ec183f845/index.html#L63-L161

- [ ] As mentioned by the previous reviewer :point_up_2: please add these cards dynamically inside the `JS` file but still your cards are not dynamically so kindly fix this issue :slightly_smiling_face:

2023-05-19 21:01 UTC, aamirkhan2478 commented on main.js
> +                    src="images/see-images/Vector.png" alt="live-link" /></a></button>
- [ ] As mentioned by the previous reviewer :point_up_2: please stick to the Figma design as much as possible but your design is still not the same as the Figma design :+1:  check below :point_down:  my video for more details :slightly_smiling_face: 

[screen-capture (8).webm](https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/45226848/fe321270-f0f8-4b45-9f73-4c12affcec7d)

| Desktop Figma Design| Mobile Figma Design |
|--------|--------|
| ![Desktop](https://user-images.githubusercontent.com/26597432/239298816-511184e1-2b59-4eb1-81c0-f8063ffc9475.png) | ![Mobile](https://user-images.githubusercontent.com/26597432/239299005-e878d636-b5b8-4bb7-8fa4-6cc64d7f3eaa.png) |

2023-05-20 00:09 UTC, evansnyamekye commented on index.html
@ aamirkhan2478 Thank you  for the review. This PR was dynamically done in main.js. Am not too sure of the branch you checked. Kindly check pop-up-menu branch that contains every js file.

2023-05-20 00:09 UTC, evansnyamekye commented on index.html
@aamirkhan2478 Thank you for the review. This PR was dynamically done in main.js. Am not too sure of the branch you checked. Kindly check pop-up-menu branch that contains every js file.

2023-05-20 00:45 UTC, evansnyamekye commented on main.js
> +                    src="images/see-images/Vector.png" alt="live-link" /></a></button>
https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/60971417/ae6b75eb-0110-412c-b943-44a846d1f0d2

2023-05-20 00:46 UTC, evansnyamekye commented on main.js
> +                    src="images/see-images/Vector.png" alt="live-link" /></a></button>
@aamirkhan2478

2023-05-20 13:41 UTC, nicupop729 reviewed
Hello @evansnyamekye  👋,

_This is an additional review as a result of the second opinion request._

Great job on the remarkable effort put into this milestone.

Upon reviewing your project, I observed that the pop-up is correctly displayed on the UI, although it is currently positioned at the bottom of the screen. However, I am confident that you will address this aspect in due course, particularly if you plan to utilize this portfolio for job applications. The subsequent reviewer will not assess this specific aspect, considering it as correctly implemented.

Unfortunately, the other aspect highlighted by both code reviewers is of great significance and has not yet been implemented.

The work cards should be entirely removed from the index.html file and generated dynamically using JavaScript, just like you did with the pop-up.
To be precise, lines 65 to 161 in the index.html file should be deleted and replaced with dynamic generation.
Refer to the project requirements screenshot below:

![image](https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/83596135/c5650188-7131-4c64-945d-e92aae475eb9)

Once this project requirement has been implemented, please utilize the dashboard to request another review.

Keep rocking 🚀!

2023-05-20 22:40 UTC, Munsa1 approved these changes
Hi @evansnyamekye, 
![congratulations-2](https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/81932478/0ef4b2db-c26b-479c-ba07-39ae8b2cdb3d)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly consider to remove the commented line of code so as to achieve a clean codebase
![image](https://github.com/evansnyamekye/Portfolio-CompleteWebsite/assets/81932478/3b8907a5-87bf-4e17-9ad3-f5b98aa6baa1)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 22:54 UTC, merged

2023-07-26 17:35 UTC, brainconnect93 reviewed
Hi @evansnyamekye,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://camo.githubusercontent.com/999c41ff216bced575a5c7873c1c4ed04ef945c867ca87788003794670ee5aa7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f785550476377453343556b586c766f6e75672f67697068792e676966">

## Invalid Code Review Request

This Project milestone is a pair-programming activity and it would be okay for you to create a new branch or repo and work with your new partner, only then your project can be approved. Thank you

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

_Cheers and Happy coding!👏👏👏_

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

-----

_Invalid Code Review Request does not count into the code reviews limit._